# Generated by Django 2.2.13 on 2020-10-23 10:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import drive.models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_auto_20201023_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='Content',
        ),
        migrations.AddField(
            model_name='file',
            name='File',
            field=models.FileField(default='abcd', upload_to=drive.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'pptx'])]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LookupWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.CharField(max_length=100)),
                ('Frequency', models.IntegerField()),
                ('File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.File')),
            ],
        ),
    ]
