# Generated by Django 2.2.13 on 2020-10-23 10:56

from django.db import migrations, models
import drive.models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_auto_20201023_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='File',
            field=models.FileField(upload_to=drive.models.user_directory_path),
        ),
    ]
